### PR TITLE
populate comments for pull requests

### PR DESCRIPTION
**Pull request by lukesmith**
Github returns a `comments` field containing the number of comments on the issue, which isn't returned on pull requests

:mag: /cc @lavapatch

### CODE REVIEW

**Comment by lavapatch** [comment]
:+1:

**Comment by ThomDietrich** [comment]
Sorry for commenting here, maybe you should activate Issues for this repository.
@lukesmith is this an active successor to the original now inactive fat/Haunt?
Is this bot fully working and are you going to continue improvements? Best!

**Comment by lukesmith** [comment]
@ThomDietrich we're not going to continue improving the bot. Our fork is currently in use but we're in the process of moving to a different solution so won't be using it going forward

**Comment by ThomDietrich** [comment]
Thanks for the answer! Would you mind telling me about the different solution? I'm looking for a bot with the capability to comment on inactive issues and assigning labels to PRs. Haunt would be great but no active developer community is a problem...

**Comment by ThomDietrich** [comment]
Just a friendly reminder. Would be nice to get some feedback. Thanks in advance!

**Pull request merged**
